// Generates src/version.ts from package.json so the SDK can report its own
// version at runtime. Runs automatically before `build` and `test`.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const out = join(root, 'src', 'version.ts');
const contents = `// AUTO-GENERATED by scripts/gen-version.mjs from package.json. Do not edit.
export const SDK_NAME = 'web';
export const SDK_VERSION = '${version}';

/** Header that tells the API which SDK and version made a request. */
export const SDK_HEADER = 'X-Rivium-SDK';
/** Its value: \`web/<version>\`. */
export const SDK_HEADER_VALUE = \`\${SDK_NAME}/\${SDK_VERSION}\`;
`;

let current = '';
try { current = readFileSync(out, 'utf8'); } catch { /* first run */ }
if (current !== contents) writeFileSync(out, contents);
