// AUTO-GENERATED by scripts/gen-version.mjs from package.json. Do not edit.
export const SDK_NAME = 'web';
export const SDK_VERSION = '0.1.3';

/** Header that tells the API which SDK and version made a request. */
export const SDK_HEADER = 'X-Rivium-SDK';
/** Its value: `web/<version>`. */
export const SDK_HEADER_VALUE = `${SDK_NAME}/${SDK_VERSION}`;
